trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '21.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npx playwright install --with-deps
  displayName: 'npm install'
  workingDirectory: '/'

- script: |
    npx playwright test
  displayName: 'Run tests'
  workingDirectory: '/'